<?php

return [

    'general' => [
        //"sn" => "報名序號",
        //"bName" => "梯次",
        //"group" => "組別",
        //"number" => "座號",
        //"is_admitted" => "錄取",
        //"is_paid" => "是否已繳費",
        //"is_cancelled" => "已取消",
        //"deleted_at" => "取消日期",
        //"bank_second_barcode" => "銷帳帳號",
        //"tax_id_no" => "統一編號",
        //"region" => "區域",
        //"created_at" => "報名日期",
        //"name" => "姓名",
        //"english_name" => "英文慣用名",
        //"gender" => "生理性別",
        //"idno" => "身分證字號",
        //"is_foreigner" => "海外身分",
        //"is_allow_notified" => "願意收到電子報",
        //"mobile" => "手機",
        //"phone_home" => "家中電話",
        // "phone_work" => "工作電話",
        // "fax" => "傳真",
        //"line" => "LineID",
        //"wechat" => "微信ID",
        //"email" => "Email",
        //"zipcode" => "郵遞區號",
        //"address" => "地址",
        //"emergency_name" => "緊急聯絡人",
        //"emergency_relationship" => "緊急聯絡人關係",
        //"emergency_mobile" => "緊急聯絡人手機",
        // "emergency_phone_home" => "緊急聯絡人家中電話",
        // "emergency_phone_work" => "緊急聯絡人工作電話",
        // "emergency_fax" => "緊急聯絡人傳真",
        //"introducer_name" => "介紹人/推薦人",
        //"introducer_relationship" => "介紹人關係",
        //"introducer_phone" => "介紹人/推薦人電話",
        //"introducer_email" => "介紹人/推薦人電子信箱",
        //"introducer_participated" => "介紹人/推薦人參加過的福智活動",
        //"portrait_agree" => "肖像權",
        //"profile_agree" => "個人資料允許",
        //"expectation" => "對活動的期望"
    ],

    'acamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "region" => "區域",
        "created_at" => "報名日期",
        "is_attend" => "回覆參加",
        "name" => "姓名",
        "gender" => "性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "is_student" => "身分",
        "mobile" => "行動電話",
        "phone_work" => "公司電話",
        "phone_home" => "住家電話",
        "email" => "電子郵件",
        "line" => "lineID",
        "class_county" => "上課地點-縣市",
        "class_subarea" => "上課地點-區",
        "introducer_name" => "介紹人姓名",
        "introducer_phone" => "介紹人電話",
        "introducer_relationship" => "介紹人關係",
        "introducer_participated" => "介紹人福智班別",
        "transportation" => "交通需求",
        "emergency_name" => "緊急聯絡人姓名",
        "emergency_mobile" => "緊急聯絡人電話",
        "emergency_relationship" => "緊急聯絡人關係",
        "profile_agree" => "個人資料",
        "is_inperson" => "是否本人填表",
        "agent_name" => "代填人姓名",
        "agent_phone" => "代填人電話",
        "agent_relationship" => "代填人關係",
        "is_manager" => "是否為主管",
        "way" => "如何得知營隊",
        "motivation" => "報名動機",
        "motivation_other" => "報名動機(其它)",
        "belief" => "宗教信仰",
        "blisswisdom_type" => "參與過福智活動",
        "blisswisdom_type_other" => "參與過福智活動(其它)",
        "industry" => "產業別",
        "job_property" => "工作屬性",
        "address" => "現居住地點",
        "unit" => "服務單位",
        "unit_county" => "服務地點-縣市",
        "unit_subarea" => "服務地點-區",
        "title" => "職稱",
        "education" => "最高學歷",
    ],

    'actcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "category" => "身份別",
        "lrclass_year" => "廣論班年份",
        "lrclass_number" => "廣論班別",
        "emergency_name" => "聯絡人姓名",
        "emergency_mobile" => "聯絡人電話",
        "emergency_relationship" => "關係",
        "mobile" => "行動電話",
        "email" => "電子郵件",
        "transportation" => "交通方式",
        "fee" => "活動費用",
        "is_attend" => "是否參加",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
    ],

    'actvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "mobile" => "行動電話",
        "email" => "電子郵件",
    ],

    'ceocamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "created_at" => "報名日期",
        "name" => "姓名",
        "files" => "上傳的檔案",
        "english_name" => "英文慣用名",
        "gender" => "生理性別",
        "is_lrclass" => "是否已加入廣論班",
        "lrclass" => "廣論班別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "carers" => "關懷員",
        "introducer_name" => "推薦人",
        "introducer_participated" => "推薦人廣論研討班別",
        "introducer_phone" => "推薦人手機號碼",
        "introducer_email" => "推薦人電子信箱",
        "introducer_relationship" => "與被推薦人關係",
        "mobile" => "手機號碼",
        "email" => "電子信箱",
        "zipcode" => "郵遞區號",
        "address" => "通訊地址",
        "line" => "LineID",
        "contact_time" => "適合聯絡時段",
        "substitute_name" => "代理人姓名",
        "substitute_phone" => "代理人聯絡電話",
        "substitute_email" => "代理人電子信箱",
        "exceptional_conditions" => "特別關懷事項",
        "unit" => "公司名稱",
        "industry" => "產業別",
        "industry_other" => "產業別:自填",
        "title" => "職稱",
        "job_property" => "職務類型",
        "job_property_other" => "職務類型:自填",
        "phone_work" => "公司電話",
        "employees" => "公司員工總數",
        "direct_managed_employees" => "所轄員工人數",
        "capital" => "資本額",
        "capital_unit" => "資本額單位",
        "org_type" => "公司組織形式",
        "org_type_other" => "公司組織形式:自填",
        "years_operation" => "公司成立幾年",
        "reasons_recommend" => "特別推薦理由",
        "profile_agree" => "個人資料允許",
        "participation_mode" => "參加營隊形式",
        "is_attend" => "參加意願",
        "reasons_online" => "選擇上述參加形式的原因",
        "bank_second_barcode" => "繳費虛擬帳號",
        "fare" => "應繳金額",
        "deposit" => "已繳金額",
    ],

    'ceovcamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "created_at" => "報名日期",
        "name" => "姓名",
        "english_name" => "英文慣用名",
        "avatar" => "大頭照",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "group_priority1" => "組別志願1",
        "group_priority2" => "組別志願2",
        "group_priority3" => "組別志願3",
        "lrclass_level" => "廣論研討班別",
        "lrclass" => "廣論研討班別詳",
        "mobile" => "手機號碼",
        "email" => "電子信箱",
        "line" => "LineID",
        "cadre_experiences" => "班級護持記錄",
        "volunteer_experiences" => "義工護持記錄",
        "transport" => "日常交通方式",
        "transport_other" => "日常交通方式:其它",
        "expertise" => "專長",
        "expertise_other" => "專長:其它",
        "language" => "語言",
        "language_other" => "語言:其它",
        "unit" => "公司名稱",
        "industry" => "產業別",
        "title" => "職稱",
        "job_property" => "職務類型",
        "employees" => "公司員工總數",
        "direct_managed_employees" => "所轄員工人數",
        "profile_agree" => "個人資料允許",
        "portrait_agree" => "肖像權",
        "introducer_name" => "邀請人"
    ],

    'ecamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "carers" => "關懷員",
        "care_log" => "關懷記錄",
        "belief" => "宗教信仰",
        "education" => "最高學歷",
        "unit" => "服務單位",
        "unit_location" => "服務單位所在地",
        "title" => "職稱",
        "job_property" => "工作屬性",
        "experience" => "經歷",
        "employees" => "公司員工人數",
        "direct_managed_employees" => "直屬管轄人數",
        "industry" => "產業別",
        "mobile" => "手機",
        "phone_work" => "公司電話",
        "phone_home" => "家中電話",
        "line" => "LineID",
        "wechat" => "微信ID",
        "email" => "Email",
        "zipcode" => "郵遞區號",
        "address" => "地址",
        "emergency_name" => "緊急聯絡人",
        "emergency_relationship" => "緊急聯絡人關係",
        "emergency_mobile" => "緊急聯絡人電話",
        "introducer_name" => "介紹人",
        "introducer_relationship" => "介紹人關係",
        "introducer_phone" => "介紹人電話",
        "introducer_participated" => "介紹人參加過的福智活動",
        "expectation" => "對活動的期望",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
        "favored_event" => "有興趣活動",
        "is_attend" => "參加意願",
        "after_camp_available_day" => "後續課程時間",
    ],

    'evcamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "role_section" => "功能組別",
        "role_position" => "職務",
        "region" => "區域",
        "created_at" => "報名日期",
        "name" => "姓名",
        "english_name" => "英文慣用名",
        "avatar" => "大頭照",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "trclass" => "儲訓班別",
        "trclass_no" => "編號",
        "group_priority1" => "組別志願1",
        "group_priority2" => "組別志願2",
        "group_priority3" => "組別志願3",
        "lrclass" => "廣論研討班別",
        "mobile" => "手機號碼",
        "email" => "電子信箱",
        "line" => "LineID",
        "cadre_experiences" => "班級護持記錄",
        "volunteer_experiences" => "義工護持記錄",
        "transport" => "日常交通方式",
        "transport_other" => "日常交通方式:其它",
        "expertise" => "專長",
        "expertise_other" => "專長:其它",
        "language" => "語言",
        "language_other" => "語言:其它",
        "participation_dates" => "護持日期",
        "stay_dates" => "住宿日期",
        "unit" => "公司名稱",
        "industry" => "產業別",
        "title" => "職稱",
        "job_property" => "職務類型",
        "employees" => "公司員工總數",
        "direct_managed_employees" => "所轄員工人數",
        "profile_agree" => "個人資料允許",
        "portrait_agree" => "肖像權",
        "introducer_name" => "邀請人"
    ],

    'hcamp' => [
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "education" => "報名者學程",
        "special_condition" => "特殊狀況",
        "traffic_depart" => "去程交通",
        "traffic_return" => "回程交通",
        // "branch_or_classroom_belongs_to" => "",
        // "class_type" => "",
        // "parent_lamrim_class" => "",
        // "is_recommended_by_reading_class" => "",
        "is_lamrim" => "父母是否參加廣論班",
        "is_child_blisswisdommed" => "孩子曾在的福智文教系統",
    ],

    'icamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "created_at" => "報名日期",
        "nationality" => "區域",
        "lrclass" => "廣論研討班別",
        "name" => "姓名",
        "gender" => "生理性別",
        "phone_home" => "在台電話",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "email" => "Email",
        "english_name" => "護照英文姓名",
        "idno" => "護照號碼或身分證字號",
        "passport_expiry_year" => "護照到期年",
        "passport_expiry_month" => "護照到期月",
        "passport_expiry_day" => "護照到期日",
        "participation_mode" => "正行報名",
        "participation_dates" => "正行報名(單日)",
        "transportation_depart" => "去程交通調查",
        "transportation_back" => "回程/單日交通調查",
        "transportation_back_location" => "回程/單日交通下車點",
        "acommodation_needs" => "住宿特殊需求",
        "dietary_needs" => "飲食特殊需求",
        "other_needs" => "其它特殊需求",
        "questions" => "備註",
    ],

    'ivcamp' => [
        "sn" => "報名序號",
        "name" => "姓名",
        "lrclass" => "廣論研討班別",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "idno" => "護身分證字號",
        "mobile" => "手機號碼",
        "line" => "LineID",
        "email" => "Email",
        "expertise" => "專長",
        "expertise_other" => "專長：自填",
        "group_priority1" => "組別志願1",
        "introducer_name" => "介紹人姓名",
    ],

    'mcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "group" => "組別",
        "name" => "姓名",
        "gender" => "生理性別",
        "age" => "年齡",
        "is_attend" => "參加意願",
        "email" => "Email",
        "mobile" => "手機號碼",
        "unit" => "服務機構",
        "title" => "職稱",
        "status" => "身分別",
        "idno" => "身分證字號",
        "medical_specialty" => "醫事人員職種類別",
        "work_category" => "長照人員職種類別",
        "profile_agree" => "個人資料允許",
        "portrait_agree" => "肖像權",
        "carers" => "關懷員",
        "care_log" => "關懷記錄",
    ],

    'mvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "lrclass" => "廣論研討班別",
        "role_section" => "功能組別",
        "role_position" => "職務",
        "email" => "Email",
        "mobile" => "手機號碼",
    ],

    'scamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "bName" => "梯次",
        "name" => "姓名",
        "english_name" => "英文姓名",
        "idno" => "身分證字號",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "phone_home" => "聯絡電話",
        "mobile" => "行動電話",
        "line" => "LineID",
        "zipcode" => "郵遞區號",
        "address" => "紙本證書郵寄地址",
        "email" => "Email",
        "unit" => "服務單位",
        "address_work" => "服務單位地址",
        "department" => "服務部門",
        "title" => "職稱",
        "seniority" => "服務年資",
        "way" => "如何得知本課程訊息",
        "way_other" => "得知管道：自填",
        "introducer_name" => "課程介紹人",
        "expectation" => "對本次課程的期待",
        "is_allow_informed" => "是否願意收到後續相關課程資訊",
        "participation_mode" => "上課方式",
        "exam_format" => "考證方式",
        "last5" => "匯款帳號後五碼",
        "remark" => "備註",
    ],

    'svcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "email" => "電子郵件",
        "mobile" => "行動電話",
        "region" => "區域",
        "line" => "LineID",
        "self_intro" => "我是誰",
    ],


    'tcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "is_admitted" => "錄取",
        "is_attend" => "參加意願",
        "region" => "區域",
        "name" => "姓名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        //"education" => "最高學歷",
        "has_license" => "教師證",
        "workshop_credit_type" => "研習時數類型",
        "idno" => "身分證字號",
        "is_educating" => "現任職於學校或教育單位",
        "school_or_course" => "任職機關/學程",
        "subject_teaches" => "任教科系/科目",
        "title" => "職稱",
        "unit" => "服務單位名稱/校名",
        "unit_county" => "服務單位所在縣市",
        "nationality" => "國籍",
        "mobile" => "行動電話",
        "phone_home" => "家中電話",
        "line" => "LineID",
        "zipcode" => "郵遞區號",
        "address" => "地址",
        "email" => "Email",
        "is_allow_notified" => "願意收到電子報",
        "emergency_name" => "緊急聯絡人",
        "emergency_relationship" => "緊急聯絡人關係",
        "emergency_mobile" => "緊急聯絡人電話1",
        "emergency_phone_home" => "緊急聯絡人電話2",
        "introducer_name" => "介紹人/推薦人",
        "introducer_relationship" => "介紹人/推薦人關係",
        "introducer_phone" => "介紹人/推薦人電話",
        "introducer_participated" => "介紹人/推薦人福智班別",
        //"never_attend_any_stay_over_tcamps" => "未曾參加過住宿型福智教師生命成長營",
        "is_attend_tcamp" => "參加過教師營",
        "tcamp_year" => "參加教師營年度",
        "is_blisswisdom" => "是否參加過福智其它活動/是否為廣論學員",
        //"blisswisdom_type" => "參加過的福智活動(選項)",
        //"blisswisdom_type_complement" => "參加過的福智活動(其它)",
        "lrclass" => "廣論班別",
        "info_source" => "得知管道",
        "interesting" => "有興趣的主題(選項)",
        "interesting_complement" => "有興趣的主題(其它)",
        "after_camp_available_day" => "營隊後方便參加時間",
        "expectation" => "對活動的期望",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
        "transportation_depart" => "去程交通",
        "transportation_back" => "回程交通",
        "carers" => "關懷員",
        "care_log" => "關懷記錄",
        "remark" => "備註",
    ],

    'tvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "mobile" => "行動電話",
        "email" => "Email",
        "region" => "區域",
        "self_intro" => "我是誰",
    ],

    'utcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "group" => "組別",
        "number" => "座號",
        "is_admitted" => "錄取",
        "is_attend" => "參加意願",
        "name" => "姓名",
        "avatar" => "大頭照",
        "gender" => "性別",
        "birthyear" => "出生年",
        "unit" => "服務學校/單位",
        "unit_county" => "服務單位所在縣市",
        "department" => "服務系所/部門",
        "position" => "身分別",
        "title" => "職稱",
        "mobile" => "聯絡電話(手機)",
        "phone_home" => "聯絡電話(H)",
        "phone_work" => "聯絡電話(O)",
        "address" => "居住縣市",
        "line" => "lineID",
        "email" => "Email",
        "info_source" => "得知管道",
        "introducer_name" => "介紹人",
        "expectation" => "對營隊的期待",
        "emergency_name" => "緊急聯絡人",
        "emergency_mobile" => "緊急聯絡人手機",
        "is_civil_certificate" => "公務員研習時數",
        "idno" => "身分證字號",
        "is_bwfoce_certificate" => "基金會研習證明",
        "invoice_type" => "發票類型",
        "tax_id" => "統編",
        "invoice_title" => "發票抬頭",
        "room_type" => "住宿需求",
        "companion_name" => "同行人姓名",
        "companion_as_roommate" => "希望同房",
        "depart_from" => "去程交通",
        "back_to" => "回程交通",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
        "care_log" => "關懷記錄",
    ],

    'utvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "mobile" => "行動電話",
        "email" => "Email",
        "region" => "區域",
        "self_intro" => "我是誰",
    ],

    'wcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "region" => "區域",
        "nationality" => "國家",
        "introducer_name" => "推薦人姓名",
        "introducer_participated" => "推薦人相關訊息",
        "introducer_phone" => "推薦人電話",
        "introducer_email" => "推薦人電子信箱",
        "name" => "姓名",
        "gender" => "性別",
        "mobile" => "聯絡電話",
        "email" => "電子信箱",
        "line" => "LineID",
        "unit" => "服務單位",
        "title" => "職稱",
        "learning_experiences" => "學習狀況",
        "volunteer_experiences" => "護持狀況",
        "speak_experiences" => "講說經驗",
        "character" => "講說特質",
        "potential" => "潛力特質",
        "comments" => "備註說明",
    ],

    'wvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "mobile" => "行動電話",
        "email" => "電子郵件",
        "line" => "LineID",
        "region" => "區域",
        "self_intro" => "我是誰",
    ],

    'nycamp' => [
        "sn" => "報名序號",
        "is_attend" => "參加意願",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "region" => "區域",
        "created_at" => "報名日期",
        "name" => "姓名",
        "chinese_first_name" => "中文名字",
        "chinese_last_name" => "中文姓氏",
        "english_name" => "英文名字",
        "english_last_name" => "英文姓氏",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "email" => "電子郵件",
        "school" => "就讀學校",
        "department" => "系所",
        "grade" => "年級",
        "mobile" => "行動電話",
        "zipcode" => "郵遞區號",
        "address" => "通訊地址",
        "info_source" => "如何得知活動",
        "introducer_name" => "介紹人姓名",
        "emergency_name" => "緊急聯絡人姓名",
        "emergency_relationship" => "緊急聯絡人關係",
        "emergency_mobile" => "緊急聯絡人電話",
        "portrait_agree" => "肖像權",
        "remark" => "備註",
    ],

    'nyvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "mobile" => "行動電話",
        "email" => "電子郵件",
        "line" => "LineID",
        "region" => "區域",
        "self_intro" => "我是誰",
    ],

    'ycamp' => [
        "sn" => "報名序號",
        "is_attend" => "參加意願",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "region" => "區域",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "nationality" => "國籍",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "habbit" => "興趣",
        "email" => "電子郵件",
        "system" => "課程學制",
        "day_nigh" => "部別",
        "school" => "就讀學校",
        "department" => "系所",
        "grade" => "年級",
        "mobile" => "行動電話",
        "phone_home" => "家中電話",
        "zipcode" => "郵遞區號",
        "address" => "通訊地址",
        "way" => "如何得知活動",
        "club" => "社團活動及擔任職務",
        "goal" => "這一生目標",
        "expectation" => "對活動的期望",
        "blisswisdom_type" => "曾參與福智活動",
        "blisswisdom_type_other" => "曾參與福智活動(其它)",
        "father_name" => "父親姓名",
        "father_lamrim" => "父親廣論班別",
        "father_phone" => "父親聯絡電話",
        "mother_name" => "母親姓名",
        "mother_lamrim" => "母親廣論班別",
        "mother_phone" => "母親聯絡電話",
        "introducer_name" => "介紹人姓名",
        "introducer_relationship" => "介紹人關係",
        "introducer_phone" => "介紹人電話",
        "introducer_participated" => "介紹人參加過的福智活動",
        "in_inperson" => "是否本人填表",
        "agent_name" => "代填人姓名",
        "agent_phone" => "代填人電話",
        "emergency_name" => "緊急聯絡人姓名",
        "emergency_relationship" => "緊急聯絡人關係",
        "emergency_mobile" => "緊急聯絡人電話",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
        "remark" => "備註",
    ],

    'yvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "mobile" => "行動電話",
        "email" => "電子郵件",
        "line" => "LineID",
        "region" => "區域",
        "self_intro" => "我是誰",
    ],

    'lrcamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "carers" => "關懷員",
        "care_log" => "關懷記錄",
        "education" => "最高學歷",
        "unit" => "服務單位",
        "unit_location" => "服務單位所在地",
        "title" => "職稱",
        "job_property" => "工作屬性",
        "experience" => "經歷",
        "employees" => "公司員工人數",
        "direct_managed_employees" => "直屬管轄人數",
        "industry" => "產業別",
        "mobile" => "手機",
        "phone_work" => "公司電話",
        "phone_home" => "家中電話",
        "line" => "LineID",
        "wechat" => "微信ID",
        "email" => "Email",
    ],

    'lrvcamp' => [
        "sn" => "報名序號",
        "created_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "mobile" => "行動電話",
        "email" => "電子郵件",
        "line" => "LineID",
        "region" => "區域",
        "self_intro" => "我是誰",
    ],

    'regions' => [
        'ycamp' => ['台北','桃園','新竹','台中','雲嘉','台南','高雄','海外'],
        'utcamp' => ['台北','桃園','新竹','台中','雲嘉','台南','高雄','海外'],
    ],

    'form_accomodation' => [
        "general" => [
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "mobile" => "手機號碼",
            //底下為空格欄位
            "empty1" => "報到",
            "empty2" => "床位",
            "empty3" => "預排",
            "empty4" => "備註(遲到)",
        ],
        "ycamp" => [
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "mobile" => "手機號碼",
            //底下為空格欄位
            "empty1" => "報到",
            "empty2" => "床位",
            "empty3" => "預排",
            "empty4" => "備註(遲到)",
        ],
    ],

    'form_contact' => [
        "general" => [
            "empty" => "確認",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "school" => "學校",
            "department" => "系所",
            "grade" => "年級",
            "mobile" => "手機號碼",
            "email" => "電子郵件",
        ],
        "ycamp" => [
            "empty" => "確認",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "school" => "學校",
            "department" => "系所",
            "grade" => "年級",
            "mobile" => "手機號碼",
            "email" => "電子郵件",
        ],
    ],

    //交通確認表(各組)
    'form_traffic_confirm' => [
        "general" => [
            "empty" => "確認",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "depart_from" => "去程交通",
            "back_to" => "回程交通",
            "fare" => "應交車資",
            "deposit" => "已交車資",
        ],
        "ycamp" => [
            "empty" => "確認",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "depart_from" => "去程交通",
            "back_to" => "回程交通",
            "fare" => "應交車資",
            "deposit" => "已交車資",
        ],
    ],

    'form_checkin' => [
        "general" => [
            "admitted_no" => "錄取編號",
            "sn" => "報名序號",
            "name" => "姓名",
            "school" => "學校",
            "department" => "系所",
            "is_attend" => "參加意願",
            "is_checkin" => "是否報到",
            "remark" => "備註",
        ],
        "ycamp" => [
            "admitted_no" => "錄取編號",
            "sn" => "報名序號",
            "name" => "姓名",
            "school" => "學校",
            "department" => "系所",
            "is_attend" => "參加意願",
            "is_checkin" => "是否報到",
            "remark" => "備註",
        ],
    ],

    //交通總表
    'form_traffic' => [
        "general" => [
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "depart_from" => "去程交通",
            "back_to" => "回程交通",
            "fare" => "應交車資",
            "deposit" => "已交車資",
            "cash" => "現金繳納",
            "is_attend" => "參加意願",
            "is_checkin" => "是否報到",
            "remark" => "備註(系統)",
            "notes" => "備註",              //非remark
            "applicant_id" => "報名序號",
        ],
        "ycamp" => [
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "depart_from" => "去程交通",
            "back_to" => "回程交通",
            "fare" => "應交車資",
            "deposit" => "已交車資",
            "cash" => "現金繳納",
            "is_attend" => "參加意願",
            "is_checkin" => "是否報到",
            "remark" => "備註(系統)",
            "notes" => "備註",              //非remark
            "applicant_id" => "報名序號",
        ],
    ],

    //搭車表(各上車處)
    'form_traffic_loc' => [
        "general" => [
            "no" => "編號",
            "empty" => "簽到",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "mobile" => "手機",
            "deposit" => "已交車資",
        ],
        "ycamp" => [
            "no" => "編號",
            "empty" => "簽到",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "mobile" => "手機",
            "deposit" => "已交車資",
        ],
    ],

    'display' => [
        'acamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'avcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
        'actcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "category" => [
                "name" => "身份別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass_year" => [
                "name" => "廣論班年份",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass_number" => [
                "name" => "廣論班別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "emergency_name" => [
                "name" => "聯絡人姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "emergency_mobile" => [
                "name" => "聯絡人電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "emergency_relationship" => [
                "name" => "關係",
                "sort" => 0,
                "for_query" => 0,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
            "transportation" => [
                "name" => "交通方式",
                "sort" => 1,
                "for_query" => 1,
            ],
            "fee" => [
                "name" => "活動費用",
                "sort" => 1,
                "for_query" => 1,
            ],
            "is_attend" => [
                "name" => "是否參加",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
        'actvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
        ],
        'ceocamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "carer" => [
                "name" => "關懷員",
                "sort" => 1,
                "for_query" => 0,
            ],
            "is_attend" => [
                "name" => "參加意願",
                "sort" => 1,
                "for_query" => 0,
            ],
            "reasons_recommend" => [
                "name" => "推薦理由",
                "sort" => 0,
                "for_query" => 0,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'ceovcamp' => [
            "batch" => [
                "name" => "報名梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "avatar" => [
                "name" => "照片",
                "sort" => 0,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass" => [
                "name" => "班別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "volunteer_experiences" => [
                "name" => "義工護持記錄",
                "sort" => 0,
                "for_query" => 1,
            ],
            "cadre_experiences" => [
                "name" => "班級護持記錄",
                "sort" => 0,
                "for_query" => 1,
            ],
            "expertise" => [
                "name" => "專長",
                "sort" => 0,
                "for_query" => 1,
            ],
            "transport" => [
                "name" => "交通方式",
                "sort" => 0,
                "for_query" => 1,
            ],
            "group_priority" => [
                "name" => "志願組別",
                "sort" => 1,
                "for_query" => 0,
            ],
        ],
        'ecamp' => [
            "id" => [
                "name" => "報名序號",
                "sort" => 1,
                "for_query" => 0,
            ],
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "carer" => [
                "name" => "關懷員",
                "sort" => 1,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "files" => [
                "name" => "上傳的檔案",
                "sort" => 0,
                "for_query" => 0,
            ],
            "birthdate" => [
                "name" => "出生年月日",
                "sort" => 1,
                "for_query" => 0,
            ],
            "unit" => [
                "name" => "服務單位",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit_location" => [
                "name" => "服務單位所在地",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 0,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 1,
                "for_query" => 0,
            ],
            "zipcode" => [
                "name" => "郵遞區號",
                "sort" => 1,
                "for_query" => 1,
            ],
            "address" => [
                "name" => "地址",
                "sort" => 1,
                "for_query" => 1,
            ],
            "is_attend" => [
                "name" => "參加意願",
                "sort" => 1,
                "for_query" => 0,
            ],
            "after_camp_available_day" => [
                "name" => "後續課程時間",
                "sort" => 1,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'evcamp' => [
            "batch" => [
                "name" => "報名梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "avatar" => [
                "name" => "照片",
                "sort" => 0,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass" => [
                "name" => "班別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "volunteer_experiences" => [
                "name" => "義工護持記錄",
                "sort" => 0,
                "for_query" => 1,
            ],
            "participation_dates" => [
                "name" => "護持日期",
                "sort" => 0,
                "for_query" => 1,
            ],
            "stay_dates" => [
                "name" => "住宿日期",
                "sort" => 0,
                "for_query" => 1,
            ],
            "expertise" => [
                "name" => "專長",
                "sort" => 0,
                "for_query" => 1,
            ],
            "transport" => [
                "name" => "交通方式",
                "sort" => 0,
                "for_query" => 1,
            ],
            "group_priority" => [
                "name" => "志願組別",
                "sort" => 1,
                "for_query" => 0,
            ],
            "participation_dates" => [
                "name" => "可護持日期",
                "sort" => 1,
                "for_query" => 0,
            ],
        ],
        'icamp' => [
            "id" => [
                "name" => "報名序號",
                "sort" => 1,
                "for_query" => 0,
            ],
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "nationality" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "phone_home" => [
                "name" => "在台電話",
                "sort" => 0,
                "for_query" => 0,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 1,
                "for_query" => 0,
            ],
            "participation_mode" => [
                "name" => "正行報名",
                "sort" => 1,
                "for_query" => 0,
            ],
            "transportation_depart" => [
                "name" => "去程交通",
                "sort" => 1,
                "for_query" => 0,
            ],
            "transportation_back" => [
                "name" => "回程/單日交通",
                "sort" => 1,
                "for_query" => 0,
            ],
            "transportation_back_location" => [
                "name" => "搭車地點",
                "sort" => 1,
                "for_query" => 0,
            ],
        ],
        'ivcamp' => [
            "id" => [
                "name" => "報名序號",
                "sort" => 1,
                "for_query" => 0,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "group_priority1" => [
                "name" => "組別志願1",
                "sort" => 1,
                "for_query" => 1,
            ],
            "expertise" => [
                "name" => "專長",
                "sort" => 0,
                "for_query" => 1,
            ],
            "expertise_other" => [
                "name" => "專長:自填",
                "sort" => 0,
                "for_query" => 1,
            ],
        ],

        'mcamp' => [
            "id" => [
                "name" => "報名序號",
                "sort" => 1,
                "for_query" => 0,
            ],
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "carer" => [
                "name" => "關懷員",
                "sort" => 1,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "服務單位",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 0,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 1,
                "for_query" => 0,
            ],
            "is_attend" => [
                "name" => "參加意願",
                "sort" => 1,
                "for_query" => 0,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'mvcamp' => [
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass" => [
                "name" => "班別",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
        'scamp' => [
            "id" => [
                "name" => "報名序號",
                "sort" => 1,
                "for_query" => 0,
            ],
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "birthyear" => [
                "name" => "出生年",
                "sort" => 1,
                "for_query" => 0,
            ],
            "unit" => [
                "name" => "服務單位",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 0,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 1,
                "for_query" => 0,
            ],
            "zipcode" => [
                "name" => "郵遞區號",
                "sort" => 1,
                "for_query" => 1,
            ],
            "address" => [
                "name" => "地址",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
        'svcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
            "self_intro" => [
                "name" => "我是誰",
                "sort" => 0,
                "for_query" => 1,
            ],
        ],
        'tcamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "number" => [
                "name" => "座號",
                "sort" => 1,
                "for_query" => 1,
            ],
            "carer" => [
                "name" => "關懷員",
                "sort" => 1,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "服務單位名稱/校名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "unit_county" => [
                "name" => "服務單位所在縣市",
                "sort" => 1,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "line" => [
                "name" => "LineID",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 0,
                "for_query" => 1,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'tvcamp' => [
            "id" => [
                "name" => "報名序號",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "生理性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 1,
            ],
            "line" => [
                "name" => "LineID",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 0,
                "for_query" => 1,
            ],
            "self_intro" => [
                "name" => "我是誰",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
        'utcamp' => [
            "created_at" => [
                "name" => "報名日期",
                "sort" => 1,
                "for_query" => 1,
            ],
            "admitted_at" => [
                "name" => "錄取日期",
                "sort" => 1,
                "for_query" => 1,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "avatar" => [
                "name" => "照片",
                "sort" => 0,
                "for_query" => 0,
            ],
            "unit" => [
                "name" => "服務單位名稱/校名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit_county" => [
                "name" => "服務單位所在縣市",
                "sort" => 1,
                "for_query" => 1,
            ],
            "department" => [
                "name" => "服務系所/部門",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "身份別",
                "sort" => 0,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "introducer_name" => [
                "name" => "介紹人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "fee" => [
                "name" => "住宿需求",
                "sort" => 1,
                "for_query" => 1,
            ],
            "deposit" => [
                "name" => "已交金額",
                "sort" => 1,
                "for_query" => 1,
            ],
            "companion_name" => [
                "name" => "同行人姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "companion_as_roommate" => [
                "name" => "希望同房",
                "sort" => 0,
                "for_query" => 0,
            ],
            "transportation_depart" => [
                "name" => "去程交通",
                "sort" => 1,
                "for_query" => 1,
            ],
            "transportation_back" => [
                "name" => "回程交通",
                "sort" => 1,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'utvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "生理性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 1,
            ],
            "line" => [
                "name" => "LineID",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 1,
                "for_query" => 1,
            ],
            "self_intro" => [
                "name" => "我是誰",
                "sort" => 1,
                "for_query" => 1,
            ]
        ],
        'wcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass" => [
                "name" => "廣論班別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
            "learning_experiences" => [
                "name" => "學習狀況",
                "sort" => 0,
                "for_query" => 1,
            ],
            "volunteer_experiences" => [
                "name" => "護持狀況",
                "sort" => 0,
                "for_query" => 1,
            ],
            "speak_experiences" => [
                "name" => "講說經驗",
                "sort" => 0,
                "for_query" => 1,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
        'wvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
            "lrclass" => [
                "name" => "廣論班別",
                "sort" => 0,
                "for_query" => 1,
            ],
            "self_intro" => [
                "name" => "我是誰",
                "sort" => 0,
                "for_query" => 1,
            ],
        ],
        'nycamp' => [
            "created_at" => [
                "name" => "報名日期",
                "sort" => 1,
                "for_query" => 1,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "school" => [
                "name" => "學校",
                "sort" => 1,
                "for_query" => 1,
            ],
            "department" => [
                "name" => "系別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "grade" => [
                "name" => "年級",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "服務單位",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
        'nyvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "self_intro" => [
                "name" => "我是誰",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'ycamp' => [
            "created_at" => [
                "name" => "報名日期",
                "sort" => 1,
                "for_query" => 1,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "school" => [
                "name" => "學校",
                "sort" => 1,
                "for_query" => 1,
            ],
            "department" => [
                "name" => "系別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "grade" => [
                "name" => "年級",
                "sort" => 1,
                "for_query" => 1,
            ],
            "way" => [
                "name" => "如何得知活動",
                "sort" => 1,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'yvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "region" => [
                "name" => "區域",
                "sort" => 1,
                "for_query" => 1,
            ],
            "self_intro" => [
                "name" => "我是誰",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
    ],
    'export4stat' => [
        'ceocamp' => [
            "deleted_at" => "取消時間",
            "applicant_id" => "報名序號",
            "bName" => "梯次",
            "admitted_no" => "組別",
            "region" => "區域",
            "created_at" => "報名日期",
            "name" => "姓名",
            "english_name" => "英文慣用名",
            "gender" => "生理性別",
            "birthyear" => "出生年",
            "carers" => "關懷員",
            "introducer_name" => "推薦人",
            "introducer_phone" => "推薦人手機號碼",
            "introducer_relationship" => "與被推薦人關係",
            "mobile" => "手機號碼",
            "LineID" => "LineID",
            "mobile" => "手機號碼",
            "contact_time" => "適合聯絡時段",
            "substitute_name" => "代理人姓名",
            "substitute_phone" => "代理人聯絡電話",
            "industry" => "產業別",
            "industry_other" => "產業別:自填",
            "job_property" => "職務類型",
            "job_property_other" => "職務類型:自填",
            "employees" => "公司員工總數",
            "direct_managed_employees" => "所轄員工人數",
            "capital" => "資本額",
            "capital_unit" => "資本額單位",
            "org_type" => "公司組織形式",
            "org_type_other" => "公司組織形式:自填",
            "years_operation" => "公司成立幾年",
            "profile_agree" => "個人資料允許",
            "is_attend" => "參加意願",
            "reasons_online" => "選擇上述參加形式的原因",
            "bank_second_barcode" => "繳費虛擬帳號",
            "lodging_fare" => "應繳金額",
            "lodging_deposit" => "已繳金額",
        ],
        'ceovcamp' => [
            "deleted_at" => "取消時間",
            "camporg_section" => "職務組別",
            "camporg_position" => "職務",
            "applicant_id" => "報名序號",
            "bName" => "梯次",
            "admitted_no" => "組別",
            "region" => "區域",
            "created_at" => "報名日期",
            "name" => "名字",
            "gender" => "生理性別",
            "birthyear" => "出生年",
            "group_priority1" => "組別志願1",
            "group_priority2" => "組別志願2",
            "group_priority3" => "組別志願3",
            "lrclass" => "廣論研討班別",
            "profile_agree" => "個人資料允許",
            "portrait_agree" => "肖像權",
            "introducer_name" => "𨘋請人",
        ],
        'ecamp' => [
            "created_at" => "報名日期",
            "applicant_id" => "報名序號",
            "bName" => "梯次",
            "region" => "區域",
            "admitted_no" => "組別",
            "name" => "姓名",
            "gender" => "生理性別",
            "birthdate" => "生日",
            "belief" => "宗教信仰",
            "education" => "最高學歷",
            "unit" => "服務單位",
            "industry" => "產業別",
            "unit_location" => "服務單位所在地",
            "title" => "職稱",
            "employees" => "公司員工人數",
            "direct_managed_employees" => "直屬管轄人數",
            "mobile" => "行動電話",
            "phone_work" => "公司電話",
            "phone_home" => "住家電話",
            "line" => "LineID",
            "wechat" => "微信ID",
            "email" => "電子郵件",
            "address" => "通訊地址",
            "info_source" => "得知管道",
            "emergency_name" => "緊急聯絡人姓名",
            "emergency_relationship" => "緊急聯絡人與學員關係",
            "emergency_mobile" => "緊急聯絡人聯絡電話",
            "introducer_name" => "介紹人姓名",
            "introducer_relationship" => "介紹人關係",
            "introducer_phone" => "介紹人聯絡電話",
            "introducer_participated" => "介紹人福智班別",
            "is_attend" => "參加營隊意願",
            "is_membership" => "參加福智會員意願",
        ],
        'evcamp' => [
            "applicant_id" => "報名序號",
            "camporg_section" => "職務組別",
            "camporg_position" => "職務",
            "region" => "區域",
            "created_at" => "報名日期",
            "name" => "姓名",
            "gender" => "生理性別",
            "birthyear" => "出生年",
            "group_priority1" => "組別志願1",
            "group_priority2" => "組別志願2",
            "group_priority3" => "組別志願3",
            "lrclass" => "廣論研討班別",
            "cadre_experiences" => "班級護持記錄",
            "volunteer_experiences" => "義工護持記錄",
            "transport" => "日常交通方式",
            "transport_other" => "日常交通方式:其它",
            "expertise" => "專長",
            "expertise_other" => "專長:其它",
            "language" => "語言",
            "language_other" => "語言:其它",
            "participation_dates" => "護持日期",
            "stay_dates" => "住宿日期",
            "is_preliminaries" => "參加全體義工提升",
            "is_cleanup" => "參加打掃法會",
            "depart_from" => "正行交通",
            "depart_from_location" => "正行交通搭車地點",
            "unit" => "公司名稱",
            "industry" => "產業別",
            "title" => "職稱",
            "job_property" => "職務類型",
            "employees" => "公司員工總數",
            "direct_managed_employees" => "所轄員工人數",
            "profile_agree" => "個人資料允許",
            "portrait_agree" => "肖像權",
            "introducer_name" => "邀請人",
        ],
        'nycamp' => [
            "applicant_id" => "報名序號",
            "created_at" => "報名日期",
            "deleted_at" => "取消日期",
            "english_name" => "英文名字",
            "english_last_name" => "英文姓氏",
            "chinese_first_name" => "中文名字",
            "chinese_last_name" => "中文姓氏",
            "is_admitted" => "是否錄取",
            "admitted_at" => "錄取日期",
            "is_attend" => "參加意願",
            "group" => "組別",
            "number" => "座號",
            "gender" => "性別",
            "birthyear" => "出生年",
            "language" => "語言偏好",
            "zipcode" => "郵遞區號",
            "addr_city" => "居住地-城市",
            "addr_state" => "居住地-州",
            "addr_country" => "居住地-國家",
            "mobile" => "行動電話",
            "email" => "電子郵件",
            "is_student" => "身分",
            "school" => "學校",
            "department" => "系所",
            "grade" => "年級",
            "unit" => "公司名稱",
            "title" => "職稱",
            "motivation" => "為何報名",
            "info_source" => "如何得知此營隊",
            "introducer_name" => "介紹人姓名",
            "emergency_name" => "緊急聯絡人姓名",
            "emergency_relationship" => "緊急聯絡人與學員關係",
            "emergency_mobile" => "緊急聯絡人行動電話",
            "emergency_phone" => "緊急聯絡人室內電話",
            "portrait_agree" => "同意聲明",
            "room_type" => "住宿選項",
            "lodging_fare" => "活動費",
            "lodging_fare_currency" => "活動費幣別",
            "depart_from" => "去程選項",
            "back_to" => "回程選項",
            "traffic_fare" => "交通費",
            "traffic_fare_currency" => "交通費幣別",
            "remark" => "備註",
            "contact_log" => "電訪記錄",
        ],
        'tcamp' => [
            "applicant_id" => "報名序號",
            "created_at" => "報名日期",
            //"bName" => "梯次",
            "group" => "組別",
            "number" => "座號",
            "is_admitted" => "錄取",
            "is_attend" => "參加意願",
            "region" => "區域",
            "name" => "姓名",
            "gender" => "生理性別",
            "birthyear" => "出生年",
            //"education" => "最高學歷",
            "has_license" => "教師證",
            "workshop_credit_type" => "研習時數類型",
            "idno" => "身分證字號",
            "is_educating" => "現任職於學校或教育單位",
            "school_or_course" => "任職機關/學程",
            "subject_teaches" => "任教科系/科目",
            "title" => "職稱",
            "unit" => "服務單位名稱/校名",
            "unit_county" => "服務單位所在縣市",
            "nationality" => "國籍",
            "mobile" => "行動電話",
            "phone_home" => "家中電話",
            "line" => "LineID",
            //"zipcode" => "郵遞區號",
            //"address" => "地址",
            "email" => "Email",
            "is_allow_notified" => "願意收到電子報",
            "emergency_name" => "緊急聯絡人",
            "emergency_relationship" => "緊急聯絡人關係",
            "emergency_mobile" => "緊急聯絡人電話1",
            "emergency_phone_home" => "緊急聯絡人電話2",
            "introducer_name" => "介紹人/推薦人",
            "introducer_relationship" => "介紹人/推薦人關係",
            "introducer_phone" => "介紹人/推薦人電話",
            "introducer_participated" => "介紹人/推薦人福智班別",
            //"never_attend_any_stay_over_tcamps" => "未曾參加過住宿型福智教師生命成長營",
            "is_attend_tcamp" => "參加過教師營",
            "tcamp_year" => "參加教師營年度",
            "is_blisswisdom" => "是否參加過福智其它活動/是否為廣論學員",
            //"blisswisdom_type" => "參加過的福智活動(選項)",
            //"blisswisdom_type_complement" => "參加過的福智活動(其它)",
            "lrclass" => "廣論班別",
            "info_source" => "得知管道",
            "interesting" => "有興趣的主題(選項)",
            "interesting_complement" => "有興趣的主題(其它)",
            //"after_camp_available_day" => "營隊後方便參加時間",
            "expectation" => "對活動的期望",
            "portrait_agree" => "肖像權",
            "profile_agree" => "個人資料允許",
            "transportation_depart" => "去程交通",
            "transportation_back" => "回程交通",
            "carers" => "關懷員",
            "care_log" => "關懷記錄",
            "remark" => "備註",
        ],
        'utcamp' => [
            "applicant_id" => "報名序號",
            "created_at" => "報名日期",
            "admitted_at" => "錄取日期",
            "group" => "組別",
            "number" => "座號",
            "is_admitted" => "錄取",
            "is_attend" => "參加意願",
            "name" => "姓名",
            "gender" => "性別",
            "birthyear" => "出生年",
            "unit" => "服務學校/單位",
            "unit_county" => "服務單位所在縣市",
            "department" => "服務系所/部門",
            "position" => "身分別",
            "title" => "職稱",
            "mobile" => "聯絡電話(手機)",
            "phone_work" => "聯絡電話(O)",
            "phone_home" => "聯絡電話(H)",
            "address" => "居住縣市",
            "line" => "lineID",
            "email" => "電子信箱",
            "info_source" => "如何得知報名訊息",
            "info_source" => "如何得知報名訊息:其它",
            "introducer_name" => "介紹人",
            "expectation" => "對營隊的期待",
            "emergency_name" => "緊急聯絡人",
            "emergency_mobile" => "緊急聯絡人手機",
            "is_civil_certificate" => "是否申請公務員研習時數",
            "idno" => "ID_number",
            "is_bwfoce_certificate" => "是否申請基金會研習證明",
            "invoice_type" => "發票類型",
            "taxid" => "統編",
            "invoice_title" => "抬頭",
            "room_type" => "住宿選項",
            "bank_second_barcode" => "繳費虛擬帳號",
            "lodging_fare" => "應繳費用",
            "lodging_deposit" => "已繳費用",
            "depart_from" => "去程交通選項",
            "back_to" => "回程交通選項",
            "care_log" => "關懷記錄",
            "companion_name" => "同行人姓名",
            "companion_as_roommate" => "希望同房",
        ],
    ],
    //please put the identifier (normally applicant_id) the first one
    'import' => [
        'ecamp' => [
            "報名序號" => "applicant_id",
            "時間戳記" => "created_at",
            "姓名" => "name",
            "生理性別" =>  "gender",
            "生日" => "birthdate",
            "宗教信仰"  => "belief",
            "最高學歷" => "education",
            "服務單位名稱" => "unit",
            "單位所在地" => "unit_location",
            "職稱" => "title",
            "公司員工人數" => "employees",
            "直屬管轄人數" => "direct_managed_employees",
            "產業別" => "industry",
            "行動電話" => "mobile",
            "公司電話" => "phone_work",
            "住家電話" => "phone_home",
            "LINE ID" => "line",
            "電子郵件" => "email",
            "通訊地址" => "address",
            "緊急聯絡人姓名" => "emergency_name",
            "緊急聯絡人關係" => "emergency_relationship",
            "緊急聯絡人電話" => "emergency_mobile",
            "介紹人姓名" => "introducer_name",
            "介紹人關係" => "introducer_relationship",
            "介紹人電話" => "introducer_phone",
            "介紹人福智班別" => "introducer_participated",
            "透過哪些管道" => "info_source",
            "加入福智" => "is_membership",
        ],

        'ceocamp' => [
            "報名序號" => "applicant_id",
            "是否參加營隊" => "is_attend",
            "住宿房型" => "room_type",
            "繳費" => "lodging_deposit",
        ],
        'nycamp' => [
            "報名序號" => "applicant_id",
            "報名費繳交" => "lodging_fare",
            "報名費幣別" => "lodging_fare_currency",
            "報名費匯率" => "fare_xrate_to_std",
            "車資繳交" => "traffic_fare",
            "車資幣別" => "traffic_fare_currency",
            "車資匯率" => "traffic_xrate_to_std",
        ],
        'utcamp' => [
            "報名序號" => "applicant_id",
            "是否參加營隊" => "is_attend",
            "住宿房型" => "room_type",
            "繳費" => "lodging_deposit",
        ],
    ],
];
